# This file was generated by GoReleaser. DO NOT EDIT.
class RapidCompose < Formula
  desc "A teminal UI to start individual services from docker-copose.yaml"
  homepage ""
  url "https://github.com/trusz/rapid-compose/releases/download/v1.1.1/rapid-compose_1.1.1_Darwin_x86_64.tar.gz"
  version "1.1.1"
  sha256 "076affac28e2d472ec0163b66194918c9fb4b8dc2521237e16d83c70511d850e"

  def install
    bin.install "rc"
  end
end
