# This file was generated by GoReleaser. DO NOT EDIT.
class RapidCompose < Formula
  desc "A teminal UI to start individual services from docker-copose.yaml"
  homepage ""
  url "https://github.com/trusz/rapid-compose/releases/download/v1.0.3/rapid-compose_1.0.3_Darwin_x86_64.tar.gz"
  version "1.0.3"
  sha256 "0544112dd6e84940a6c4c08c865e5149edbf6109331dafaf527df422b769cc28"

  def install
    bin.install "rapid-compose"
  end
end
